services:
  db:
    image: postgres:15
    environment:
      - DB_USER=${DB_USER}
      - DB_ENV=${DB_ENV}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_USER=${DB_USER}
      - DB_ENV=${DB_ENV}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    volumes:
      - .:/app

volumes:
  postgres_data:
